In [1]:
import numpy as np

In [6]:
# 1. Compute the multiplication of the following matrices:
#[[1, 0], [0, 1]]
#[[1, 2], [3, 4]]

matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[1, 2], [3, 4]])

np.dot(matrix_1,matrix_2)


array([[1, 2],
       [3, 4]])

In [11]:
# 2. Generate an array of length 3n filled with the cyclic pattern 1, 2, 3.
n = 4

cyclic_array = np.array([1, 2, 3] * n)

cyclic_array

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
# 3. Create a 10×10 matrix of zeros and then "frame" it with a border of ones.

zero_matrix = np.array([[0] * 10]*10)
add_row = np.array([1] * 10)
add_col = np.array([1] * 12)

zero_matrix = np.insert(zero_matrix, zero_matrix.shape[0], add_row, axis=0)
zero_matrix = np.insert(zero_matrix, 0, add_row, axis=0)

zero_matrix = np.insert(zero_matrix, 0, add_col, axis=1)
zero_matrix = np.insert(zero_matrix, zero_matrix.shape[1], add_col, axis=1)

zero_matrix

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [85]:
# 4. Create a random 3×5 array using the np.random.rand(3, 5) function and compute: the sum of all the entries, the sum of the rows and the sum of the columns. 
#(many Numpy functions have an optional axis= argument!)

matrix_3 = np.random.rand(3,5)
print(f'Sum columns: {np.sum(matrix_3, axis=0)}')
print(f'Sum row: {np.sum(matrix_3, axis=1)}')
print(f'Sum matrix: {np.sum(matrix_3)}')

Sum columns: [1.5862685  0.71505227 1.86591078 1.81006591 1.8441482 ]
Sum row: [3.00142399 0.96922886 3.8507928 ]
Sum matrix: 7.8214456449666


In [60]:
# 5. Given the following arrays representing logical values (0 = False, 1 = True) 
# compute the logical AND and logical OR operations for every pair of values of the two arrays: [1, 1, 0, 0] [1, 0, 1, 0] 
# Hint: you may need to set the data type (dtype) of the array's elements to 'bool'

matrix_4 = np.array([1, 1, 0, 0])
matrix_5 = np.array([1, 0, 1, 0])
and_matrix = np.logical_and(matrix_4, matrix_5, dtype='bool')
or_matrix = np.logical_or(matrix_4, matrix_5, dtype='bool')
print(f'AND Matrix: {and_matrix}')
print(f'OR Matrix: {or_matrix}')

AND Matrix: [ True False False False]
OR Matrix: [ True  True  True False]


In [64]:
# 6. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

matrix_6 = np.array([1, 2, 0, 0, 4, 0])

print(f'Non Zero indice: {np.nonzero(matrix_6)}')

Non Zero indice: (array([0, 1, 4]),)


In [73]:
# 7. Create a 8×8 array with random values and find minimum and maximum value

matrix_7 = np.random.rand(8,8)
print(f'Max value: {np.max(matrix_7)}')
print(f'Min value: {np.min(matrix_7)}')

Max value: 0.9940368946592678
Min value: 0.023158924993278207


In [84]:
# 8. Create a 8×8 array with random natural values from the range (1-100) on the diagonal, other values should be 0. 
# Hint: You can use numpy's 'eye' function.

matrix_8 = np.random.randint(1, 101, size = (8,8))
map_matrix = np.eye(8, dtype='int')

matrix_8 * map_matrix

array([[88,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 37,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 17,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 39,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 19]])

In [90]:
# 9. Write a function which creates an n×n matrix with (i,j)-entry equal to i+j.

n = 8
matrix_9 = np.zeros((n,n), dtype='int')

def matrix_func(n, matrix):
    for i in range(n):
        for j in range(n):
            matrix[i,j] = i + j
    return matrix

matrix_func(n, matrix_9)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])

In [95]:
# 10.  Write a function which creates an n×n matrix with rows having subsequent values multiplied by the row's number. For example for n = 4:
# [[0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9], [0, 4, 8, 12]]

n = 5
matrix_10 = np.zeros((n,n), dtype='int')

def subsequent_matrix(n, matrix):
    for i in range(n):
        for j in range(1,n):
            matrix[i,j] = matrix[i,j-1] + i + 1
    return matrix

subsequent_matrix(n, matrix_10)


array([[ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20]])